/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scholarshipgui;

import admin.adminDashboard;
import config.dbConnect;
import config.passwordHasher;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
       
         this.viewicon.setVisible(false);
       
    }
    public static String email1,username1;
     public boolean duplicateChecker() {
    dbConnect db = new dbConnect();
    boolean isDuplicate = false;

    try {
        String query = "SELECT username, email FROM tbl_user WHERE username = ? OR email = ?";
        PreparedStatement pstmt = db.getConnection().prepareStatement(query);
        pstmt.setString(1, username.getText());
        pstmt.setString(2, email.getText());
        ResultSet resultSet = pstmt.executeQuery();

        while (resultSet.next()) { 
            String existingEmail = resultSet.getString("email");
            String existingUsername = resultSet.getString("username");

            if (existingEmail.equals(email.getText())) {
                JOptionPane.showMessageDialog(null, "Email is Already Used");
                email.setText("");
                isDuplicate = true;
            }
            if (existingUsername.equals(username.getText())) {
                JOptionPane.showMessageDialog(null, "Username is Already Used");
                username.setText("");
                isDuplicate = true;
            }
        }

        resultSet.close();
        pstmt.close();
    } catch (SQLException e) {
        System.out.println("Error: " + e.getMessage());
    }

    return isDuplicate;
}
    
     private boolean isEmailValid(String email) {
      
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
      
        Pattern pattern = Pattern.compile(emailRegex);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }

    Color hover = new Color (255,255,255);
    Color defaultcolor = new Color  (102,102,102);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        registernav = new javax.swing.JPanel();
        register = new javax.swing.JLabel();
        lgnav3 = new javax.swing.JPanel();
        lgnav4 = new javax.swing.JLabel();
        registernav2 = new javax.swing.JPanel();
        lgnav8 = new javax.swing.JLabel();
        lgnav9 = new javax.swing.JPanel();
        lgnav10 = new javax.swing.JLabel();
        registernav3 = new javax.swing.JPanel();
        lgnav11 = new javax.swing.JLabel();
        lgnav12 = new javax.swing.JPanel();
        lgnav13 = new javax.swing.JLabel();
        registernav4 = new javax.swing.JPanel();
        lgnav14 = new javax.swing.JLabel();
        lgnav15 = new javax.swing.JPanel();
        lgnav16 = new javax.swing.JLabel();
        registernav5 = new javax.swing.JPanel();
        lgnav17 = new javax.swing.JLabel();
        lgnav18 = new javax.swing.JPanel();
        lgnav19 = new javax.swing.JLabel();
        registernav6 = new javax.swing.JPanel();
        lgnav20 = new javax.swing.JLabel();
        lgnav21 = new javax.swing.JPanel();
        lgnav22 = new javax.swing.JLabel();
        registernav7 = new javax.swing.JPanel();
        lgnav23 = new javax.swing.JLabel();
        lgnav24 = new javax.swing.JPanel();
        lgnav25 = new javax.swing.JLabel();
        cancelnav = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        iconhide1 = new javax.swing.JLabel();
        viewicon = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REGISTRATION FORM");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 540, 40));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 110, 30));

        username.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 420, 50));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("First Name:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 110, 30));

        fname.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 420, 50));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Last Name:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 110, 30));

        lname.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        jPanel1.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 420, 50));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 110, 30));

        email.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 420, 50));

        contact.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 420, 50));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Type:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 110, 30));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/register11.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Password:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 130, 30));

        registernav.setBackground(new java.awt.Color(102, 102, 102));
        registernav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registernavMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registernavMouseExited(evt);
            }
        });
        registernav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        register.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        register.setForeground(new java.awt.Color(51, 51, 51));
        register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        register.setText("REGISTER");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerMouseEntered(evt);
            }
        });
        registernav.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        lgnav3.setBackground(new java.awt.Color(204, 255, 255));
        lgnav3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lgnav3MouseExited(evt);
            }
        });
        lgnav3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav4.setText("REGISTER");
        lgnav4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav4MouseEntered(evt);
            }
        });
        lgnav3.add(lgnav4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 20));

        registernav.add(lgnav3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, 150, 40));

        registernav2.setBackground(new java.awt.Color(204, 255, 255));
        registernav2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registernav2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registernav2MouseExited(evt);
            }
        });
        registernav2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav8.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav8.setText("REGISTER");
        lgnav8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav8MouseEntered(evt);
            }
        });
        registernav2.add(lgnav8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        lgnav9.setBackground(new java.awt.Color(204, 255, 255));
        lgnav9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lgnav9MouseExited(evt);
            }
        });
        lgnav9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav10.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav10.setText("REGISTER");
        lgnav10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav10MouseEntered(evt);
            }
        });
        lgnav9.add(lgnav10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 20));

        registernav2.add(lgnav9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, 150, 40));

        registernav3.setBackground(new java.awt.Color(204, 255, 255));
        registernav3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registernav3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registernav3MouseExited(evt);
            }
        });
        registernav3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav11.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav11.setText("REGISTER");
        lgnav11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav11MouseEntered(evt);
            }
        });
        registernav3.add(lgnav11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        lgnav12.setBackground(new java.awt.Color(204, 255, 255));
        lgnav12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lgnav12MouseExited(evt);
            }
        });
        lgnav12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav13.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav13.setText("REGISTER");
        lgnav13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav13MouseEntered(evt);
            }
        });
        lgnav12.add(lgnav13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 20));

        registernav3.add(lgnav12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, 150, 40));

        registernav2.add(registernav3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 150, 40));

        registernav.add(registernav2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 150, 40));

        registernav4.setBackground(new java.awt.Color(204, 255, 255));
        registernav4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registernav4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registernav4MouseExited(evt);
            }
        });
        registernav4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav14.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav14.setText("REGISTER");
        lgnav14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav14MouseEntered(evt);
            }
        });
        registernav4.add(lgnav14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        lgnav15.setBackground(new java.awt.Color(204, 255, 255));
        lgnav15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lgnav15MouseExited(evt);
            }
        });
        lgnav15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav16.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav16.setText("REGISTER");
        lgnav16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav16MouseEntered(evt);
            }
        });
        lgnav15.add(lgnav16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 20));

        registernav4.add(lgnav15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, 150, 40));

        registernav5.setBackground(new java.awt.Color(204, 255, 255));
        registernav5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registernav5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registernav5MouseExited(evt);
            }
        });
        registernav5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav17.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav17.setText("REGISTER");
        lgnav17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav17MouseEntered(evt);
            }
        });
        registernav5.add(lgnav17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        lgnav18.setBackground(new java.awt.Color(204, 255, 255));
        lgnav18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lgnav18MouseExited(evt);
            }
        });
        lgnav18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav19.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav19.setText("REGISTER");
        lgnav19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav19MouseEntered(evt);
            }
        });
        lgnav18.add(lgnav19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 20));

        registernav5.add(lgnav18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, 150, 40));

        registernav4.add(registernav5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 150, 40));

        registernav6.setBackground(new java.awt.Color(204, 255, 255));
        registernav6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registernav6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registernav6MouseExited(evt);
            }
        });
        registernav6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav20.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav20.setText("REGISTER");
        lgnav20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav20MouseEntered(evt);
            }
        });
        registernav6.add(lgnav20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        lgnav21.setBackground(new java.awt.Color(204, 255, 255));
        lgnav21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lgnav21MouseExited(evt);
            }
        });
        lgnav21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav22.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav22.setText("REGISTER");
        lgnav22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav22MouseEntered(evt);
            }
        });
        lgnav21.add(lgnav22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 20));

        registernav6.add(lgnav21, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, 150, 40));

        registernav7.setBackground(new java.awt.Color(204, 255, 255));
        registernav7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registernav7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registernav7MouseExited(evt);
            }
        });
        registernav7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav23.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav23.setText("REGISTER");
        lgnav23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav23MouseEntered(evt);
            }
        });
        registernav7.add(lgnav23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        lgnav24.setBackground(new java.awt.Color(204, 255, 255));
        lgnav24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav24MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lgnav24MouseExited(evt);
            }
        });
        lgnav24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav25.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav25.setText("REGISTER");
        lgnav25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav25MouseEntered(evt);
            }
        });
        lgnav24.add(lgnav25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 20));

        registernav7.add(lgnav24, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, 150, 40));

        registernav6.add(registernav7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 150, 40));

        registernav4.add(registernav6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 150, 40));

        registernav.add(registernav4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 150, 40));

        jPanel1.add(registernav, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 150, 40));

        cancelnav.setBackground(new java.awt.Color(102, 102, 102));
        cancelnav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelnavMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelnavMouseExited(evt);
            }
        });
        cancelnav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CANCEL");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        cancelnav.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 20));

        jPanel1.add(cancelnav, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 150, 40));

        type.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type of User", "Admin", "Applicant", "Scholarship Providers/Committee" }));
        type.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 420, 50));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Contact:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 110, 30));

        iconhide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconhide.png"))); // NOI18N
        iconhide1.setText("jLabel1");
        iconhide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconhide1MousePressed(evt);
            }
        });
        jPanel1.add(iconhide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 30, 30));

        viewicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewicon.png"))); // NOI18N
        viewicon.setText("jLabel1");
        viewicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewiconMousePressed(evt);
            }
        });
        jPanel1.add(viewicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 30, 30));

        pass.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        pass.setEchoChar('\u2022');
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 420, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseEntered

    }//GEN-LAST:event_registerMouseEntered

    private void registernavMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernavMouseEntered
        registernav.setBackground(hover);
    }//GEN-LAST:event_registernavMouseEntered

    private void registernavMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernavMouseExited
        registernav.setBackground(defaultcolor);
    }//GEN-LAST:event_registernavMouseExited

    private void lgnav4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav4MouseEntered

    private void lgnav3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav3MouseEntered

    private void lgnav3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav3MouseExited

    private void cancelnavMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelnavMouseEntered
        cancelnav.setBackground(hover);
    }//GEN-LAST:event_cancelnavMouseEntered

    private void cancelnavMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelnavMouseExited
        cancelnav.setBackground(defaultcolor);
    }//GEN-LAST:event_cancelnavMouseExited

    private void lgnav8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav8MouseEntered

    private void lgnav10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav10MouseEntered

    private void lgnav9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav9MouseEntered

    private void lgnav9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav9MouseExited

    private void lgnav11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav11MouseEntered

    private void lgnav13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav13MouseEntered

    private void lgnav12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav12MouseEntered

    private void lgnav12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav12MouseExited

    private void registernav3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav3MouseEntered

    private void registernav3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav3MouseExited

    private void registernav2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav2MouseEntered

    private void registernav2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav2MouseExited

    private void lgnav14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav14MouseEntered

    private void lgnav16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav16MouseEntered

    private void lgnav15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav15MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav15MouseEntered

    private void lgnav15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav15MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav15MouseExited

    private void lgnav17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav17MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav17MouseEntered

    private void lgnav19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav19MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav19MouseEntered

    private void lgnav18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav18MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav18MouseEntered

    private void lgnav18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav18MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav18MouseExited

    private void registernav5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav5MouseEntered

    private void registernav5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav5MouseExited

    private void lgnav20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav20MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav20MouseEntered

    private void lgnav22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav22MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav22MouseEntered

    private void lgnav21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav21MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav21MouseEntered

    private void lgnav21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav21MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav21MouseExited

    private void lgnav23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav23MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav23MouseEntered

    private void lgnav25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav25MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav25MouseEntered

    private void lgnav24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav24MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav24MouseEntered

    private void lgnav24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav24MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav24MouseExited

    private void registernav7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav7MouseEntered

    private void registernav7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav7MouseExited

    private void registernav6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav6MouseEntered

    private void registernav6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav6MouseExited

    private void registernav4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav4MouseEntered

    private void registernav4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav4MouseExited

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
      
        dbConnect db = new dbConnect();
      
        if(username.getText().isEmpty() || fname.getText().isEmpty() || lname.getText().isEmpty() || email.getText().isEmpty() || contact.getText().isEmpty() 
                || pass.getText().isEmpty() || pass.getText().isEmpty()){
               JOptionPane.showMessageDialog(null, "All fields required");
               
        }else if(!isEmailValid(email.getText())){
            JOptionPane.showMessageDialog(null, "Invalid email format");
        }else if(duplicateChecker()){
            System.out.println("Duplicate Existed");
        }
        else if(!contact.getText().matches("\\d+")){
            JOptionPane.showMessageDialog(null, "Contact number must only contains digit");
        }else if(contact.getText().length() > 11){
            JOptionPane.showMessageDialog(null, "Contact number exceeded");
        }else if(pass.getText().length() < 8){
            JOptionPane.showMessageDialog(null, "Password must be at least 8 characters long");
        
        }else if(type.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Please select a Type of User"); 
        }else{
            
            try{
                String pass1 = passwordHasher.hashPassword(pass.getText());
        if (db.insertData("INSERT INTO tbl_user (username, f_name, l_name, email, contact, type, pass, status, registration_date, sec_ques1, answer_1, sec_ques2, answer_2, image) "
    + "VALUES ('" + username.getText() + "', '" + fname.getText() + "', '" + lname.getText() + "', '" + email.getText() + "', "
    + "'" + contact.getText() + "', '" + type.getSelectedItem() + "', '" + pass1 + "', "
    + "'Pending', CURRENT_TIMESTAMP, 'N/A', 'N/A', 'N/A', 'N/A', 'N/A')") == 1) {

            
            
            JOptionPane.showMessageDialog(null, "Submitted Successfully");
           adminDashboard ad  = new adminDashboard();
          ad.loadRecentUsers();
            LoginForm lf = new LoginForm();
            lf.setVisible(true);
            this.dispose();
          }else{
              JOptionPane.showMessageDialog(null, "Connection Error");
          }
            }catch(NoSuchAlgorithmException e){
                System.out.println(""+e);
        }
        }
        
    }//GEN-LAST:event_registerMouseClicked

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void viewiconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewiconMousePressed
        viewicon.setVisible(false);
        iconhide1.setVisible(true);
        pass.setEchoChar('*');
    }//GEN-LAST:event_viewiconMousePressed

    private void iconhide1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconhide1MousePressed
      
        viewicon.setVisible(true);
        iconhide1.setVisible(false);
        pass.setEchoChar((char)0);
        
    }//GEN-LAST:event_iconhide1MousePressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       LoginForm lf = new LoginForm();
       lf.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cancelnav;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel iconhide1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel lgnav10;
    private javax.swing.JLabel lgnav11;
    private javax.swing.JPanel lgnav12;
    private javax.swing.JLabel lgnav13;
    private javax.swing.JLabel lgnav14;
    private javax.swing.JPanel lgnav15;
    private javax.swing.JLabel lgnav16;
    private javax.swing.JLabel lgnav17;
    private javax.swing.JPanel lgnav18;
    private javax.swing.JLabel lgnav19;
    private javax.swing.JLabel lgnav20;
    private javax.swing.JPanel lgnav21;
    private javax.swing.JLabel lgnav22;
    private javax.swing.JLabel lgnav23;
    private javax.swing.JPanel lgnav24;
    private javax.swing.JLabel lgnav25;
    private javax.swing.JPanel lgnav3;
    private javax.swing.JLabel lgnav4;
    private javax.swing.JLabel lgnav8;
    private javax.swing.JPanel lgnav9;
    private javax.swing.JTextField lname;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel register;
    private javax.swing.JPanel registernav;
    private javax.swing.JPanel registernav2;
    private javax.swing.JPanel registernav3;
    private javax.swing.JPanel registernav4;
    private javax.swing.JPanel registernav5;
    private javax.swing.JPanel registernav6;
    private javax.swing.JPanel registernav7;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JTextField username;
    private javax.swing.JLabel viewicon;
    // End of variables declaration//GEN-END:variables
}
