/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scholarcommitte;

import admin.adminDashboard;
import java.awt.Color;
import config.dbConnect;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class addScholarship extends javax.swing.JFrame {

    /**
     * Creates new form addScholarship
     */
    public addScholarship() {
        initComponents();
    }
    
Color hover = new Color (255,255,255);
    Color defaultcolor = new Color  (102,102,102);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        capacity = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        registernav = new javax.swing.JPanel();
        lgnav3 = new javax.swing.JPanel();
        lgnav4 = new javax.swing.JLabel();
        registernav2 = new javax.swing.JPanel();
        lgnav8 = new javax.swing.JLabel();
        lgnav9 = new javax.swing.JPanel();
        lgnav10 = new javax.swing.JLabel();
        registernav3 = new javax.swing.JPanel();
        lgnav11 = new javax.swing.JLabel();
        lgnav12 = new javax.swing.JPanel();
        lgnav13 = new javax.swing.JLabel();
        registernav4 = new javax.swing.JPanel();
        lgnav14 = new javax.swing.JLabel();
        lgnav15 = new javax.swing.JPanel();
        lgnav16 = new javax.swing.JLabel();
        registernav5 = new javax.swing.JPanel();
        lgnav17 = new javax.swing.JLabel();
        lgnav18 = new javax.swing.JPanel();
        lgnav19 = new javax.swing.JLabel();
        registernav6 = new javax.swing.JPanel();
        lgnav20 = new javax.swing.JLabel();
        lgnav21 = new javax.swing.JPanel();
        lgnav22 = new javax.swing.JLabel();
        registernav7 = new javax.swing.JPanel();
        lgnav23 = new javax.swing.JLabel();
        lgnav24 = new javax.swing.JPanel();
        lgnav25 = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        cancelnav = new javax.swing.JPanel();
        backdash1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        require = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        gpa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        annincome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        des = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        deadline = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SCHOLARSHIP ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 610, 40));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Capacity:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 140, 50));

        capacity.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        capacity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        capacity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        capacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacityActionPerformed(evt);
            }
        });
        jPanel1.add(capacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 290, 50));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addform.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        registernav.setBackground(new java.awt.Color(102, 102, 102));
        registernav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registernavMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registernavMouseExited(evt);
            }
        });
        registernav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav3.setBackground(new java.awt.Color(204, 255, 255));
        lgnav3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lgnav3MouseExited(evt);
            }
        });
        lgnav3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav4.setText("REGISTER");
        lgnav4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav4MouseEntered(evt);
            }
        });
        lgnav3.add(lgnav4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 20));

        registernav.add(lgnav3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, 150, 40));

        registernav2.setBackground(new java.awt.Color(204, 255, 255));
        registernav2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registernav2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registernav2MouseExited(evt);
            }
        });
        registernav2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav8.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav8.setText("REGISTER");
        lgnav8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav8MouseEntered(evt);
            }
        });
        registernav2.add(lgnav8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        lgnav9.setBackground(new java.awt.Color(204, 255, 255));
        lgnav9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lgnav9MouseExited(evt);
            }
        });
        lgnav9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav10.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav10.setText("REGISTER");
        lgnav10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav10MouseEntered(evt);
            }
        });
        lgnav9.add(lgnav10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 20));

        registernav2.add(lgnav9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, 150, 40));

        registernav3.setBackground(new java.awt.Color(204, 255, 255));
        registernav3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registernav3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registernav3MouseExited(evt);
            }
        });
        registernav3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav11.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav11.setText("REGISTER");
        lgnav11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav11MouseEntered(evt);
            }
        });
        registernav3.add(lgnav11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        lgnav12.setBackground(new java.awt.Color(204, 255, 255));
        lgnav12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lgnav12MouseExited(evt);
            }
        });
        lgnav12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav13.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav13.setText("REGISTER");
        lgnav13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav13MouseEntered(evt);
            }
        });
        lgnav12.add(lgnav13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 20));

        registernav3.add(lgnav12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, 150, 40));

        registernav2.add(registernav3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 150, 40));

        registernav.add(registernav2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 150, 40));

        registernav4.setBackground(new java.awt.Color(204, 255, 255));
        registernav4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registernav4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registernav4MouseExited(evt);
            }
        });
        registernav4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav14.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav14.setText("REGISTER");
        lgnav14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav14MouseEntered(evt);
            }
        });
        registernav4.add(lgnav14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        lgnav15.setBackground(new java.awt.Color(204, 255, 255));
        lgnav15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lgnav15MouseExited(evt);
            }
        });
        lgnav15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav16.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav16.setText("REGISTER");
        lgnav16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav16MouseEntered(evt);
            }
        });
        lgnav15.add(lgnav16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 20));

        registernav4.add(lgnav15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, 150, 40));

        registernav5.setBackground(new java.awt.Color(204, 255, 255));
        registernav5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registernav5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registernav5MouseExited(evt);
            }
        });
        registernav5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav17.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav17.setText("REGISTER");
        lgnav17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav17MouseEntered(evt);
            }
        });
        registernav5.add(lgnav17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        lgnav18.setBackground(new java.awt.Color(204, 255, 255));
        lgnav18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lgnav18MouseExited(evt);
            }
        });
        lgnav18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav19.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav19.setText("REGISTER");
        lgnav19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav19MouseEntered(evt);
            }
        });
        lgnav18.add(lgnav19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 20));

        registernav5.add(lgnav18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, 150, 40));

        registernav4.add(registernav5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 150, 40));

        registernav6.setBackground(new java.awt.Color(204, 255, 255));
        registernav6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registernav6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registernav6MouseExited(evt);
            }
        });
        registernav6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav20.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav20.setText("REGISTER");
        lgnav20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav20MouseEntered(evt);
            }
        });
        registernav6.add(lgnav20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        lgnav21.setBackground(new java.awt.Color(204, 255, 255));
        lgnav21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lgnav21MouseExited(evt);
            }
        });
        lgnav21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav22.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav22.setText("REGISTER");
        lgnav22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav22MouseEntered(evt);
            }
        });
        lgnav21.add(lgnav22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 20));

        registernav6.add(lgnav21, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, 150, 40));

        registernav7.setBackground(new java.awt.Color(204, 255, 255));
        registernav7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registernav7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registernav7MouseExited(evt);
            }
        });
        registernav7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav23.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav23.setText("REGISTER");
        lgnav23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav23MouseEntered(evt);
            }
        });
        registernav7.add(lgnav23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        lgnav24.setBackground(new java.awt.Color(204, 255, 255));
        lgnav24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav24MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lgnav24MouseExited(evt);
            }
        });
        lgnav24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lgnav25.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lgnav25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgnav25.setText("REGISTER");
        lgnav25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgnav25MouseEntered(evt);
            }
        });
        lgnav24.add(lgnav25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 20));

        registernav7.add(lgnav24, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, 150, 40));

        registernav6.add(registernav7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 150, 40));

        registernav4.add(registernav6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 150, 40));

        registernav.add(registernav4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 150, 40));

        add.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(51, 51, 51));
        add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add.setText("ADD");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        registernav.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 20));

        jPanel1.add(registernav, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 710, 150, 40));

        cancelnav.setBackground(new java.awt.Color(102, 102, 102));
        cancelnav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelnavMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelnavMouseExited(evt);
            }
        });
        cancelnav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backdash1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        backdash1.setForeground(new java.awt.Color(51, 51, 51));
        backdash1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backdash1.setText("CANCEL");
        backdash1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backdash1MouseClicked(evt);
            }
        });
        cancelnav.add(backdash1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 20));

        jPanel1.add(cancelnav, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 710, 150, 40));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Deadline:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 580, 140, 30));

        require.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        require.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        require.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        require.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requireActionPerformed(evt);
            }
        });
        jPanel1.add(require, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 360, 150));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("GPA:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 190, 30));

        gpa.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        gpa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gpa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        gpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpaActionPerformed(evt);
            }
        });
        jPanel1.add(gpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 290, 50));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Annual Income:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 190, 40));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Annual Income:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 190, 40));

        annincome.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        annincome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        annincome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        annincome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annincomeActionPerformed(evt);
            }
        });
        jPanel1.add(annincome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 290, 50));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Benefits:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 200, 60));

        amount.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        amount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        jPanel1.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 290, 50));

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Scholarship Name: ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 170, 30));

        sname.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        sname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        sname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snameActionPerformed(evt);
            }
        });
        jPanel1.add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 290, 50));

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Description:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 170, 30));

        des.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        des.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        des.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desActionPerformed(evt);
            }
        });
        jPanel1.add(des, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 360, 120));

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Requirements:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 180, 30));
        jPanel1.add(deadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 640, 360, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelnavMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelnavMouseExited
        cancelnav.setBackground(defaultcolor);
    }//GEN-LAST:event_cancelnavMouseExited

    private void cancelnavMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelnavMouseEntered
        cancelnav.setBackground(hover);
    }//GEN-LAST:event_cancelnavMouseEntered

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
   

                dbConnect db = new dbConnect();

                if (sname.getText().isEmpty() || gpa.getText().isEmpty() || annincome.getText().isEmpty() || 
                    amount.getText().isEmpty() || capacity.getText().isEmpty() || des.getText().isEmpty() || 
                    require.getText().isEmpty() || deadline.getDate() == null) {

                    JOptionPane.showMessageDialog(null, "All fields are required");
                } 
                                else if (!gpa.getText().matches("^(Above|Below|Minimum|Between)?\\s*\\d+(\\.\\d+)?(\\s*(-|to|and)\\s*\\d+(\\.\\d+)?)?$")) {
                    JOptionPane.showMessageDialog(null, "Invalid GPA format!\nExamples: 3.5, 2.0 - 3.5, Above 3.0, Between 2.0 and 3.5");
                    return;
                }
                else if (!annincome.getText().matches("^[a-zA-Z\\s]*\\d*[a-zA-Z\\s]*$")) {
    JOptionPane.showMessageDialog(null, "Annual income should be a number or contain descriptive text (e.g., 'Above 50000', 'No income')");
} 
else if (!amount.getText().matches("^[a-zA-Z\\s]*\\d*[a-zA-Z\\s]*$")) {
    JOptionPane.showMessageDialog(null, "Fund amount should be a number or contain descriptive text (e.g., 'Up to 50000')");
} 
                else if (!capacity.getText().matches("\\d+")) {
                    JOptionPane.showMessageDialog(null, "Capacity should only contain numbers");
                } 
                else {

                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    String deadlineDate = sdf.format(deadline.getDate());


                    String query = "INSERT INTO tbl_scholarship (s_name, description, GPA, requirements, annual_income, fund_amount, capacity, status, deadline) " 
                                 + "VALUES ('"+sname.getText()+"', '"+des.getText()+"', '"+gpa.getText()+"', '"+require.getText()+"', '" 
                                 + annincome.getText()+"', '"+amount.getText()+"', '"+capacity.getText()+"', 'Available', '"+deadlineDate+"')";

                    if (db.insertData(query) == 1) {
                        JOptionPane.showMessageDialog(null, "Scholarship Submitted Successfully");


                        adminDashboard sd = new adminDashboard();
                        sd.setVisible(true);
                        this.dispose();
                    }
}

    }//GEN-LAST:event_addMouseClicked

    private void registernavMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernavMouseExited
        registernav.setBackground(defaultcolor);
    }//GEN-LAST:event_registernavMouseExited

    private void registernavMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernavMouseEntered
        registernav.setBackground(hover);
    }//GEN-LAST:event_registernavMouseEntered

    private void registernav4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav4MouseExited

    private void registernav4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav4MouseEntered

    private void registernav6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav6MouseExited

    private void registernav6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav6MouseEntered

    private void registernav7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav7MouseExited

    private void registernav7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav7MouseEntered

    private void lgnav24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav24MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav24MouseExited

    private void lgnav24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav24MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav24MouseEntered

    private void lgnav25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav25MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav25MouseEntered

    private void lgnav23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav23MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav23MouseEntered

    private void lgnav21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav21MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav21MouseExited

    private void lgnav21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav21MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav21MouseEntered

    private void lgnav22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav22MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav22MouseEntered

    private void lgnav20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav20MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav20MouseEntered

    private void registernav5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav5MouseExited

    private void registernav5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav5MouseEntered

    private void lgnav18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav18MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav18MouseExited

    private void lgnav18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav18MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav18MouseEntered

    private void lgnav19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav19MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav19MouseEntered

    private void lgnav17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav17MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav17MouseEntered

    private void lgnav15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav15MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav15MouseExited

    private void lgnav15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav15MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav15MouseEntered

    private void lgnav16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav16MouseEntered

    private void lgnav14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav14MouseEntered

    private void registernav2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav2MouseExited

    private void registernav2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav2MouseEntered

    private void registernav3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav3MouseExited

    private void registernav3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registernav3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_registernav3MouseEntered

    private void lgnav12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav12MouseExited

    private void lgnav12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav12MouseEntered

    private void lgnav13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav13MouseEntered

    private void lgnav11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav11MouseEntered

    private void lgnav9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav9MouseExited

    private void lgnav9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav9MouseEntered

    private void lgnav10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav10MouseEntered

    private void lgnav8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav8MouseEntered

    private void lgnav3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav3MouseExited

    private void lgnav3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav3MouseEntered

    private void lgnav4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgnav4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnav4MouseEntered

    private void capacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capacityActionPerformed

    private void requireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requireActionPerformed

    private void gpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpaActionPerformed

    private void annincomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annincomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annincomeActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    private void snameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snameActionPerformed

    private void desActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desActionPerformed

    private void backdash1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backdash1MouseClicked
       scho_table st = new scho_table();
       st.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_backdash1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addScholarship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addScholarship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addScholarship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addScholarship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addScholarship().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JTextField amount;
    private javax.swing.JTextField annincome;
    private javax.swing.JLabel backdash1;
    private javax.swing.JPanel cancelnav;
    private javax.swing.JTextField capacity;
    private com.toedter.calendar.JDateChooser deadline;
    private javax.swing.JTextField des;
    private javax.swing.JTextField gpa;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lgnav10;
    private javax.swing.JLabel lgnav11;
    private javax.swing.JPanel lgnav12;
    private javax.swing.JLabel lgnav13;
    private javax.swing.JLabel lgnav14;
    private javax.swing.JPanel lgnav15;
    private javax.swing.JLabel lgnav16;
    private javax.swing.JLabel lgnav17;
    private javax.swing.JPanel lgnav18;
    private javax.swing.JLabel lgnav19;
    private javax.swing.JLabel lgnav20;
    private javax.swing.JPanel lgnav21;
    private javax.swing.JLabel lgnav22;
    private javax.swing.JLabel lgnav23;
    private javax.swing.JPanel lgnav24;
    private javax.swing.JLabel lgnav25;
    private javax.swing.JPanel lgnav3;
    private javax.swing.JLabel lgnav4;
    private javax.swing.JLabel lgnav8;
    private javax.swing.JPanel lgnav9;
    private javax.swing.JPanel registernav;
    private javax.swing.JPanel registernav2;
    private javax.swing.JPanel registernav3;
    private javax.swing.JPanel registernav4;
    private javax.swing.JPanel registernav5;
    private javax.swing.JPanel registernav6;
    private javax.swing.JPanel registernav7;
    private javax.swing.JTextField require;
    private javax.swing.JTextField sname;
    // End of variables declaration//GEN-END:variables
}
