/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scholarcommitte;

import config.dbConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author user
 */
public class applicants extends javax.swing.JFrame {

    /**
     * Creates new form applicants
     */
    public applicants() {
        initComponents();
        displayUsers();
          searchfield.getDocument().addDocumentListener(new DocumentListener() {
    @Override
    public void insertUpdate(DocumentEvent e) {
        searchApplicationTable(); // Call searchTable when text is added
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
       searchApplicationTable(); // Call searchTable when text is removed
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        searchApplicationTable(); // Needed for text formatting changes (rare)
    }
});
    }
   private void searchApplicationTable() {
    String searchText = searchfield.getText().toLowerCase().trim(); // Normalize input

    dbConnect db = new dbConnect();
    Connection conn = db.getConnection();

    if (conn == null) {
        JOptionPane.showMessageDialog(this, "Database connection failed. Please check your settings.");
        return;
    }

    String query;
    boolean isSearchEmpty = searchText.isEmpty();

    if (isSearchEmpty) {
        query = "SELECT * FROM tbl_records"; 
    } else {
        query = "SELECT * FROM tbl_records WHERE LOWER(fname) LIKE ? OR LOWER(status) LIKE ? OR LOWER(status_release) LIKE ?";
    }

    try (PreparedStatement statement = conn.prepareStatement(query)) {
        if (!isSearchEmpty) {
            String likeText = "%" + searchText + "%";
            statement.setString(1, likeText);
            statement.setString(2, likeText);
            statement.setString(3, likeText);
        }

        try (ResultSet resultSet = statement.executeQuery()) {
            tbl_app.setModel(DbUtils.resultSetToTableModel(resultSet));

            if (tbl_app.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "No matching records found.");
            }
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error executing query: " + ex.getMessage());
        ex.printStackTrace();
    } finally {
        db.close();
    }
}


   public void displayUsers() {
    try {
        dbConnect db = new dbConnect();

        String query = "SELECT " +
                       "r.r_id, r.user_id, r.fname, r.lname, r.u_email, r.s_id, " +
                       "s.s_name AS 'Scholarship Name', " +
                       "r.GPA, r.requirements_pass, r.annual_income, r.date_submit, r.status " +
                       "FROM tbl_records r " +
                       "JOIN tbl_scholarship s ON r.s_id = s.s_id";

        ResultSet rs = db.getData(query);
        tbl_app.setModel(DbUtils.resultSetToTableModel(rs));
        rs.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Data Retrieval Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        refreshnav = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        editnav = new javax.swing.JPanel();
        edit = new javax.swing.JLabel();
        acc_name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_app = new javax.swing.JTable();
        searchfield = new javax.swing.JTextField();
        searchnav = new javax.swing.JPanel();
        search = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("_____________________________________");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 280, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finallogoadmin.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 130, 110));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconforsholarship.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 260, 260));

        refreshnav.setBackground(new java.awt.Color(255, 255, 255));
        refreshnav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jLabel8.setText(" Back");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        refreshnav.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 170, 30));

        jPanel2.add(refreshnav, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 240, 50));

        editnav.setBackground(new java.awt.Color(255, 255, 255));
        editnav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edit.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        edit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edituser.png"))); // NOI18N
        edit.setText(" Edit");
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        editnav.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 120, 30));

        jPanel2.add(editnav, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 240, 50));

        acc_name.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        acc_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_name.setText("Hello, Admin");
        jPanel2.add(acc_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 190, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 280, 680));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("APPLICATION'S");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 610, 50));

        tbl_app.setBackground(new java.awt.Color(153, 153, 153));
        tbl_app.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        tbl_app.setForeground(new java.awt.Color(255, 255, 255));
        tbl_app.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_app);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 960, 520));

        searchfield.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        searchfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102), 3));
        searchfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchfieldActionPerformed(evt);
            }
        });
        jPanel1.add(searchfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 850, 40));

        searchnav.setBackground(new java.awt.Color(255, 255, 255));
        searchnav.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102), 3));
        searchnav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seach.png"))); // NOI18N
        searchnav.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 40));

        jPanel1.add(searchnav, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 130, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1294, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
  int rowIndex = tbl_app.getSelectedRow();

if (rowIndex < 0) {
    JOptionPane.showMessageDialog(null, "Please select an item.", "Click an Item", JOptionPane.WARNING_MESSAGE);
} else {
    try {
        dbConnect dc = new dbConnect();
        TableModel tbl = tbl_app.getModel();

        // Safely get r_id (assuming it's in column 0 and it's an integer)
        int selectedId = Integer.parseInt(tbl.getValueAt(rowIndex, 0).toString());

        // Fetch application data
        ResultSet rs = dc.getData("SELECT * FROM tbl_records WHERE r_id = " + selectedId);
        updateApplications af = new updateApplications();
        if (rs.next()) {
            String status = rs.getString("status");

            // 🔒 If status is Approved, show message and stop
            if ("Approved".equalsIgnoreCase(status)) {
                JOptionPane.showMessageDialog(null, "This application has already been approved and cannot be edited.", "Edit Not Allowed", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            // Fetch the scholarship details using s_id
            int scholarshipId = rs.getInt("s_id");
            ResultSet scholarshipRS = dc.getData("SELECT * FROM tbl_scholarship WHERE s_id = " + scholarshipId);
            
            if (scholarshipRS.next()) {
                // Populate the scholarship details in the form
                String scholarshipRequirements = scholarshipRS.getString("requirements");
                String scholarshipGPA = scholarshipRS.getString("GPA");
                String scholarshipIncome = scholarshipRS.getString("annual_income");
                String scholarshipDate = scholarshipRS.getString("Deadline");  // Assuming there's a deadline column

                // You can show these details in text fields or labels
                af.scholarshipRequirements.setText(scholarshipRequirements);
                af.scholarshipGPA.setText(scholarshipGPA);
                af.scholarshipIncome.setText(scholarshipIncome);
                af.scholarshipDeadline.setText(scholarshipDate);
            }

            // Populate the application details in the form
            
            af.setVisible(true);

            af.r_id.setText(String.valueOf(rs.getInt("r_id")));
            af.u_id.setText(String.valueOf(rs.getInt("user_id")));
            af.s_id.setText(String.valueOf(rs.getInt("s_id")));
            af.fname.setText(rs.getString("fname"));
            af.lname.setText(rs.getString("lname"));
            af.email.setText(rs.getString("u_email"));
            af.contact.setText(rs.getString("contact"));
            af.address.setText(rs.getString("address"));
            af.gpa.setText(rs.getString("GPA"));
            af.ann.setText(rs.getString("annual_income"));
            af.require.setText(rs.getString("requirements_pass"));
            af.status.setSelectedItem(status);
            af.date_submit.setText(String.valueOf(rs.getDate("date_submit")));

            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Application not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Unexpected Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    }//GEN-LAST:event_editMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        sDashBoard sd = new sDashBoard();
        sd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void searchfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(applicants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(applicants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(applicants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(applicants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new applicants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc_name;
    private javax.swing.JLabel edit;
    private javax.swing.JPanel editnav;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel refreshnav;
    private javax.swing.JLabel search;
    private javax.swing.JTextField searchfield;
    private javax.swing.JPanel searchnav;
    private javax.swing.JTable tbl_app;
    // End of variables declaration//GEN-END:variables
}
